name = "CooccurrenceRegression"
uuid = "b11753cd-0d5a-47ad-8b8f-99db3fa4a09b"
authors = ["Arthur <arn203@exeter.ac.uk> and contributors"]
version = "1.0.0-DEV"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Mooncake = "0.4"
Reexport = "1.2"
Turing = "0.39"
julia = "1.10.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
